apiVersion: v1
kind: Service
metadata:
  name: java-maven-app
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: java-maven-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
